version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: DeepL-Slack-Translator-Node
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
